### ISSUE TITLE
Backup option after a certain period

### ISSUE THREAD

**Issue by AltemirX** [ViktorJp/BACKUPMON#57]
Please add a backup option after a certain period, and not daily. For example, every Wednesday or every 5th day of the month

**Comment by ViktorJp** [comment]
> Please add a backup option after a certain period, and not daily. For example, every Wednesday or every 5th day of the month

You can actually do this already by just creating your own cron job schedule. Just make sure you call "sh /jffs/scripts/backupmon.sh -backup" on the dates/times you want to run the script.
